// 명명규칙은 xxxxImg로 통일
export { default as UpArrowImg } from './arrow_up.png';
export { default as 배너광고1Img } from './bannerAd1.png';
export { default as 배너광고2Img } from './bannerAd2.png';
export { default as CheckImg } from './check.png';
export { default as CheckboxImg } from './checkbox@2x.png';
export { default as BackwardArrow } from './chevron.backward.png';
export { default as ForwardArrow } from './chevron.forward.png';
export { default as 익스피디아Img } from './expedia.png';
export { default as JejuFlightImg } from './Group 145.png';
export { default as DanangFlightImg } from './Group 146.png';
export { default as NewDeliFlightImg } from './Group 147.png';
export { default as UBTFlightImg } from './Group 148.png';
export { default as SydneyFlightImg } from './Group 149.png';
export { default as SingaporeFlightImg } from './Group 150.png';
export { default as HeadBanner } from './headbanner.png';
export { default as AirplaneImg } from './icn_airplane@2x.png';
export { default as ArrowImg } from './icn_arrow.png';
export { default as DownArrow } from './icn_arrow_default@2x.png';
export { default as BedImg } from './icn_bed@2x.png';
export { default as CarImg } from './icn_car@2x.png';
export { default as HeartImg } from './icn_heart.png';
export { default as HeartBlackImg } from './icn_heart@2x.png';
export { default as SearchImg } from './icn_search.png';
export { default as StarImg } from './icn_star@2x.png';
export { default as RightArticleImg2 } from './image.png';
export { default as RightArticleImg1 } from './image-1.png';
export { default as AdImg } from './img_ad.png';
export { default as AirBusanImg } from './img_airbusan.png';
export { default as AirSeoulImg } from './img_airseoul@2x.png';
export { default as AnaImg } from './img_ana.png';
export { default as AsianaImg } from './img_asiana@2x.png';
export { default as TwayImg } from './img_card_l_1_airline.png';
export { default as VietJetImg } from './img_card_l_2_airline.png';
export { default as AirIndiaImg } from './img_card_l_3_airline.png';
export { default as MIATImg } from './img_card_l_4_airline.png';
export { default as JetstarImg } from './img_card_l_5_airline.png';
export { default as ScootImg } from './img_card_l_6_airline.png';
export { default as JapanImg } from './img_card_m_1.png';
export { default as PhilippinesImg } from './img_card_m_2.png';
export { default as UKImg } from './img_card_m_3.png';
export { default as SwissImg } from './img_card_m_4.png';
export { default as CanadaImg } from './img_card_m_5.png';
export { default as EmiratesImg } from './img_card_m_6.png';
export { default as HawaiiImg } from './img_card_m_7.png';
export { default as ThailandImg } from './img_card_m_8.png';
export { default as FranceImg } from './img_card_m_9 (1).png';
export { default as TaiwanImg } from './img_card_m_9.png';
export { default as AustrailiaImg } from './img_card_m_10 (1).png';
export { default as NewZealandImg } from './img_card_m_10.png';
export { default as SingaporeImg } from './img_card_m_11 (1).png';
export { default as IcelandImg } from './img_card_m_11.png';
export { default as ItalyImg } from './img_card_m_12 (1).png';
export { default as MexicoImg } from './img_card_m_12.png';
export { default as AtlantaImg } from './img_card_s_1.png';
export { default as BeijingImg } from './img_card_s_2.png';
export { default as HKImg } from './img_card_s_3.png';
export { default as RomaImg } from './img_card_s_4.png';
export { default as ChicagoImg } from './img_card_s_5.png';
export { default as MoscowImg } from './img_card_s_6.png';
export { default as OsakaImg } from './img_card_s_7.png';
export { default as LAImg } from './img_card_s_8.png';
export { default as DanangImg } from './img_card_s_9 (2).png';
export { default as SeattleImg } from './img_card_s_9.png';
export { default as DubaiImg } from './img_card_s_10 (2).png';
export { default as BangkokImg } from './img_card_s_10.png';
export { default as KyotoImg } from './img_card_s_11 (2).png';
export { default as ParisImg } from './img_card_s_11.png';
export { default as PrahaImg } from './img_card_s_12 (2).png';
export { default as NYImg } from './img_card_s_12.png';
export { default as GotoBgImg } from './img_gotobackground.png';
export { default as HotelImg1 } from './img_hotel_1@2x.png';
export { default as HotelImg2 } from './img_hotel_2@2x.png';
export { default as HotelImg3 } from './img_hotel_3@2x.png';
export { default as HotelImg4 } from './img_hotel_4@2x.png';
export { default as HotelImg5 } from './img_hotel_5.png';
export { default as HotelImg6 } from './img_hotel_6.png';
export { default as HotelImg7 } from './img_hotel_7.png';
export { default as HotelImg8 } from './img_hotel_8.png';
export { default as JejuAirImg } from './img_jejuair.png';
export { default as JinAirImg } from './img_jinair@2x.png';
export { default as KoreanAirImg } from './img_koreanair@2x.png';
export { default as MainImg } from './img_main.png';
export { default as PeachImg } from './img_peach.png';
export { default as 인터파크Img } from './interpark.png';
export { default as LeafImg } from './leaf.fill@2x.png';
export { default as 마이리얼트립Img } from './myrealtrip.png';
export { default as LeftArticleImg } from './Rectangle 34624743.png';
export { default as TabGraphImg } from './tabbox_depart_graph_default.png';
export { default as 내일투어Img } from './tommorow-tour.png';
export { default as 트리플Img } from './triple.png';
export { default as 참좋은여행Img } from './verygood-travel.png';
export { default as 트립닷컴Img } from './verygood-travel.png';
export { default as 노랑풍선Img } from './yellow-ballon.png';
