// 명명규칙은 xxxxImg로 통일
export { default as BackwardArrow } from './chevron.backward.png';
export { default as ForwardArrow } from './chevron.forward.png';
export { default as HeadBanner } from './headbanner.png';
export { default as ArrowImg } from './icn_arrow.png';
export { default as HeartImg } from './icn_heart.png';
export { default as HeartBlackImg } from './icn_heart@2x.png';
export { default as StarImg } from './icn_star@2x.png';
export { default as HotelImg1 } from './img_hotel_1@2x.png';
export { default as HotelImg2 } from './img_hotel_2@2x.png';
export { default as HotelImg3 } from './img_hotel_3@2x.png';
export { default as HotelImg4 } from './img_hotel_4@2x.png';
export { default as HotelImg5 } from './img_hotel_5.png';
export { default as HotelImg6 } from './img_hotel_6.png';
export { default as HotelImg7 } from './img_hotel_7.png';
export { default as HotelImg8 } from './img_hotel_8.png';
export { default as KoreanAirImg } from './img_koreanair@2x.png';
export { default as MainImg } from './img_main.png';
export { default as LeafImg } from './leaf.fill@2x.png';
