// 명명규칙은 xxxxImg로 통일
export { default as BackwardArrow } from './chevron.backward.png';
export { default as ForwardArrow } from './chevron.forward.png';
export { default as HeadBanner } from './headbanner.png';
export { default as HeartImg } from './icn_heart.png';
export { default as StarImg } from './icn_star@2x.png';
export { default as PhilippinesImg } from './image (1).png';
export { default as UKImg } from './image (2).png';
export { default as SwissImg } from './image (3).png';
export { default as CanadaImg } from './image (4).png';
export { default as EmiratesImg } from './image (5).png';
export { default as HawaiiImg } from './image (6).png';
export { default as ThailandImg } from './image (7).png';
export { default as TaiwanImg } from './image (8).png';
export { default as NewZealandImg } from './image (9).png';
export { default as MexicoImg } from './image (10).png';
export { default as FranceImg } from './image (11).png';
export { default as AustrailiaImg } from './image (12).png';
export { default as SingaporeImg } from './image (13).png';
export { default as ItalyImg } from './image (14).png';
export { default as IcelandImg } from './image (15).png';
export { default as JapanImg } from './image.png';
export { default as HotelImg1 } from './img_hotel_1@2x.png';
export { default as HotelImg2 } from './img_hotel_2@2x.png';
export { default as HotelImg3 } from './img_hotel_3@2x.png';
export { default as HotelImg4 } from './img_hotel_4@2x.png';
export { default as HotelImg5 } from './img_hotel_5.png';
export { default as HotelImg6 } from './img_hotel_6.png';
export { default as HotelImg7 } from './img_hotel_7.png';
export { default as HotelImg8 } from './img_hotel_8.png';
